### ISSUE TITLE
Is project alive? It's not even compilable.

### ISSUE THREAD

**Issue by PhantomYdn** [socialsensor/graphdb-benchmarks#5]

**Comment by sarovios** [comment]
Hello,

you are right. The problem is that when this benchmark was built we used snapshot of orientdb latest build in order to take advantage of the new features orientdb devs were introducing. Unfortunately, this snapshot is not available from the Maven repository. The code needs refactoring and upgrade to the latest release of all the compared graph dbs. This will be performed as soon as possible.

Sorry for any inconvenience.
